name: Run PHPUnit Tests

on:
  pull_request:
    branches: [ master ]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repo code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        tools: phpunit # Ensure phpunit is available
        coverage: xdebug # Enable xdebug for coverage

    - name: Update dependencies
      run: composer update --prefer-dist --no-progress

    - name: Run PHPUnit tests and generate report
      run: vendor/bin/phpunit --configuration phpunit.xml --coverage-html coverage-report

    - name: Archive coverage reports
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage-report/
